package net.badlion.gspigot.protocol107;

import java.util.HashMap;
import java.util.Map;

import org.spigotmc.ProtocolInjector;

import net.minecraft.server.Packet;
import net.minecraft.server.PacketPlayInAbilities;
import net.minecraft.server.PacketPlayInArmAnimation;
import net.minecraft.server.PacketPlayInBlockDig;
import net.minecraft.server.PacketPlayInBlockPlace;
import net.minecraft.server.PacketPlayInBoatMove;
import net.minecraft.server.PacketPlayInChat;
import net.minecraft.server.PacketPlayInClientCommand;
import net.minecraft.server.PacketPlayInCloseWindow;
import net.minecraft.server.PacketPlayInCustomPayload;
import net.minecraft.server.PacketPlayInEnchantItem;
import net.minecraft.server.PacketPlayInEntityAction;
import net.minecraft.server.PacketPlayInFlying;
import net.minecraft.server.PacketPlayInHeldItemSlot;
import net.minecraft.server.PacketPlayInKeepAlive;
import net.minecraft.server.PacketPlayInLook;
import net.minecraft.server.PacketPlayInPosition;
import net.minecraft.server.PacketPlayInPositionLook;
import net.minecraft.server.PacketPlayInSetCreativeSlot;
import net.minecraft.server.PacketPlayInSettings;
import net.minecraft.server.PacketPlayInSteerVehicle;
import net.minecraft.server.PacketPlayInTabComplete;
import net.minecraft.server.PacketPlayInTeleportAccept;
import net.minecraft.server.PacketPlayInTransaction;
import net.minecraft.server.PacketPlayInUpdateSign;
import net.minecraft.server.PacketPlayInUseEntity;
import net.minecraft.server.PacketPlayInUseItem;
import net.minecraft.server.PacketPlayInVehicleMove;
import net.minecraft.server.PacketPlayInWindowClick;
import net.minecraft.server.PacketPlayOutAbilities;
import net.minecraft.server.PacketPlayOutAnimation;
import net.minecraft.server.PacketPlayOutAttachEntity;
import net.minecraft.server.PacketPlayOutBed;
import net.minecraft.server.PacketPlayOutBlockAction;
import net.minecraft.server.PacketPlayOutBlockBreakAnimation;
import net.minecraft.server.PacketPlayOutBlockChange;
import net.minecraft.server.PacketPlayOutBossBar;
import net.minecraft.server.PacketPlayOutChat;
import net.minecraft.server.PacketPlayOutCloseWindow;
import net.minecraft.server.PacketPlayOutCollect;
import net.minecraft.server.PacketPlayOutCooldown;
import net.minecraft.server.PacketPlayOutCustomPayload;
import net.minecraft.server.PacketPlayOutEntity;
import net.minecraft.server.PacketPlayOutEntityDestroy;
import net.minecraft.server.PacketPlayOutEntityEffect;
import net.minecraft.server.PacketPlayOutEntityEquipment;
import net.minecraft.server.PacketPlayOutEntityHeadRotation;
import net.minecraft.server.PacketPlayOutEntityLook;
import net.minecraft.server.PacketPlayOutEntityMetadata;
import net.minecraft.server.PacketPlayOutEntityStatus;
import net.minecraft.server.PacketPlayOutEntityTeleport;
import net.minecraft.server.PacketPlayOutEntityVelocity;
import net.minecraft.server.PacketPlayOutExperience;
import net.minecraft.server.PacketPlayOutExplosion;
import net.minecraft.server.PacketPlayOutGameStateChange;
import net.minecraft.server.PacketPlayOutHeldItemSlot;
import net.minecraft.server.PacketPlayOutKeepAlive;
import net.minecraft.server.PacketPlayOutKickDisconnect;
import net.minecraft.server.PacketPlayOutLogin;
import net.minecraft.server.PacketPlayOutMap;
import net.minecraft.server.PacketPlayOutMapChunk;
import net.minecraft.server.PacketPlayOutMount;
import net.minecraft.server.PacketPlayOutMultiBlockChange;
import net.minecraft.server.PacketPlayOutNamedEntitySpawn;
import net.minecraft.server.PacketPlayOutNamedSoundEffect;
import net.minecraft.server.PacketPlayOutOpenSignEditor;
import net.minecraft.server.PacketPlayOutOpenWindow;
import net.minecraft.server.PacketPlayOutPlayerInfo;
import net.minecraft.server.PacketPlayOutPosition;
import net.minecraft.server.PacketPlayOutRelEntityMove;
import net.minecraft.server.PacketPlayOutRelEntityMoveLook;
import net.minecraft.server.PacketPlayOutRemoveEntityEffect;
import net.minecraft.server.PacketPlayOutRespawn;
import net.minecraft.server.PacketPlayOutScoreboardDisplayObjective;
import net.minecraft.server.PacketPlayOutScoreboardObjective;
import net.minecraft.server.PacketPlayOutScoreboardScore;
import net.minecraft.server.PacketPlayOutScoreboardTeam;
import net.minecraft.server.PacketPlayOutSetSlot;
import net.minecraft.server.PacketPlayOutSpawnEntity;
import net.minecraft.server.PacketPlayOutSpawnEntityExperienceOrb;
import net.minecraft.server.PacketPlayOutSpawnEntityLiving;
import net.minecraft.server.PacketPlayOutSpawnEntityPainting;
import net.minecraft.server.PacketPlayOutSpawnEntityWeather;
import net.minecraft.server.PacketPlayOutSpawnPosition;
import net.minecraft.server.PacketPlayOutStatistic;
import net.minecraft.server.PacketPlayOutTabComplete;
import net.minecraft.server.PacketPlayOutTileEntityData;
import net.minecraft.server.PacketPlayOutTransaction;
import net.minecraft.server.PacketPlayOutUnloadChunk;
import net.minecraft.server.PacketPlayOutUpdateAttributes;
import net.minecraft.server.PacketPlayOutUpdateHealth;
import net.minecraft.server.PacketPlayOutUpdateSign;
import net.minecraft.server.PacketPlayOutUpdateTime;
import net.minecraft.server.PacketPlayOutVehicleMove;
import net.minecraft.server.PacketPlayOutWindowData;
import net.minecraft.server.PacketPlayOutWindowItems;
import net.minecraft.server.PacketPlayOutWorldEvent;
import net.minecraft.server.PacketPlayOutWorldParticles;

public class Packets {
	public static final Class[] INBOUND = new Class[30];

	static {
		INBOUND[0] = PacketPlayInTeleportAccept.class;
		INBOUND[1] = PacketPlayInTabComplete.class;
		INBOUND[2] = PacketPlayInChat.class;
		INBOUND[3] = PacketPlayInClientCommand.class;
		INBOUND[4] = PacketPlayInSettings.class;
		INBOUND[5] = PacketPlayInTransaction.class;
		INBOUND[6] = PacketPlayInEnchantItem.class;
		INBOUND[7] = PacketPlayInWindowClick.class;
		INBOUND[8] = PacketPlayInCloseWindow.class;
		INBOUND[9] = PacketPlayInCustomPayload.class;
		INBOUND[10] = PacketPlayInUseEntity.class;
		INBOUND[11] = PacketPlayInKeepAlive.class;
		INBOUND[12] = PacketPlayInPosition.class;
		INBOUND[13] = PacketPlayInPositionLook.class;
		INBOUND[14] = PacketPlayInLook.class;
		INBOUND[15] = PacketPlayInFlying.class;
		INBOUND[16] = PacketPlayInVehicleMove.class;
		INBOUND[17] = PacketPlayInBoatMove.class;
		INBOUND[18] = PacketPlayInAbilities.class;
		INBOUND[19] = PacketPlayInBlockDig.class;
		INBOUND[20] = PacketPlayInEntityAction.class;
		INBOUND[21] = PacketPlayInSteerVehicle.class;
		INBOUND[23] = PacketPlayInHeldItemSlot.class;
		INBOUND[24] = PacketPlayInSetCreativeSlot.class;
		INBOUND[25] = PacketPlayInUpdateSign.class;
		INBOUND[26] = PacketPlayInArmAnimation.class;
		INBOUND[28] = PacketPlayInBlockPlace.class;
		INBOUND[29] = PacketPlayInUseItem.class;
	}

	public static final Map<Class<? extends Packet>, Integer> OUTBOUND = new HashMap<Class<? extends Packet>, Integer>();

	static {
		OUTBOUND.put(PacketPlayOutSpawnEntity.class, Integer.valueOf(0));
		OUTBOUND.put(PacketPlayOutSpawnEntityExperienceOrb.class, Integer.valueOf(1));
		OUTBOUND.put(PacketPlayOutSpawnEntityWeather.class, Integer.valueOf(2));
		OUTBOUND.put(PacketPlayOutSpawnEntityLiving.class, Integer.valueOf(3));
		OUTBOUND.put(PacketPlayOutSpawnEntityPainting.class, Integer.valueOf(4));
		OUTBOUND.put(PacketPlayOutNamedEntitySpawn.class, Integer.valueOf(5));
		OUTBOUND.put(PacketPlayOutAnimation.class, Integer.valueOf(6));
		OUTBOUND.put(PacketPlayOutStatistic.class, Integer.valueOf(7));
		OUTBOUND.put(PacketPlayOutBlockBreakAnimation.class, Integer.valueOf(8));
		OUTBOUND.put(PacketPlayOutTileEntityData.class, Integer.valueOf(9));
		OUTBOUND.put(PacketPlayOutBlockAction.class, Integer.valueOf(10));
		OUTBOUND.put(PacketPlayOutBlockChange.class, Integer.valueOf(11));
		OUTBOUND.put(PacketPlayOutBossBar.class, Integer.valueOf(12));
		OUTBOUND.put(PacketPlayOutTabComplete.class, Integer.valueOf(14));
		OUTBOUND.put(PacketPlayOutChat.class, Integer.valueOf(15));
		OUTBOUND.put(PacketPlayOutMultiBlockChange.class, Integer.valueOf(16));
		OUTBOUND.put(PacketPlayOutTransaction.class, Integer.valueOf(17));
		OUTBOUND.put(PacketPlayOutCloseWindow.class, Integer.valueOf(18));
		OUTBOUND.put(PacketPlayOutOpenWindow.class, Integer.valueOf(19));
		OUTBOUND.put(PacketPlayOutWindowItems.class, Integer.valueOf(20));
		OUTBOUND.put(PacketPlayOutWindowData.class, Integer.valueOf(21));
		OUTBOUND.put(PacketPlayOutSetSlot.class, Integer.valueOf(22));
		OUTBOUND.put(PacketPlayOutCooldown.class, Integer.valueOf(23));
		OUTBOUND.put(PacketPlayOutCustomPayload.class, Integer.valueOf(24));
		OUTBOUND.put(PacketPlayOutNamedSoundEffect.class, Integer.valueOf(25));
		OUTBOUND.put(PacketPlayOutKickDisconnect.class, Integer.valueOf(26));
		OUTBOUND.put(PacketPlayOutEntityStatus.class, Integer.valueOf(27));
		OUTBOUND.put(PacketPlayOutExplosion.class, Integer.valueOf(28));
		OUTBOUND.put(PacketPlayOutUnloadChunk.class, Integer.valueOf(29));
		OUTBOUND.put(PacketPlayOutGameStateChange.class, Integer.valueOf(30));
		OUTBOUND.put(PacketPlayOutKeepAlive.class, Integer.valueOf(31));
		OUTBOUND.put(PacketPlayOutMapChunk.class, Integer.valueOf(32));
		OUTBOUND.put(PacketPlayOutWorldEvent.class, Integer.valueOf(33));
		OUTBOUND.put(PacketPlayOutWorldParticles.class, Integer.valueOf(34));
		OUTBOUND.put(PacketPlayOutLogin.class, Integer.valueOf(35));
		OUTBOUND.put(PacketPlayOutMap.class, Integer.valueOf(36));
		OUTBOUND.put(PacketPlayOutRelEntityMove.class, Integer.valueOf(37));
		OUTBOUND.put(PacketPlayOutRelEntityMoveLook.class, Integer.valueOf(38));
		OUTBOUND.put(PacketPlayOutEntityLook.class, Integer.valueOf(39));
		OUTBOUND.put(PacketPlayOutEntity.class, Integer.valueOf(40));
		OUTBOUND.put(PacketPlayOutVehicleMove.class, Integer.valueOf(41));
		OUTBOUND.put(PacketPlayOutOpenSignEditor.class, Integer.valueOf(42));
		OUTBOUND.put(PacketPlayOutAbilities.class, Integer.valueOf(43));
		OUTBOUND.put(PacketPlayOutPlayerInfo.class, Integer.valueOf(45));
		OUTBOUND.put(PacketPlayOutPosition.class, Integer.valueOf(46));
		OUTBOUND.put(PacketPlayOutBed.class, Integer.valueOf(47));
		OUTBOUND.put(PacketPlayOutEntityDestroy.class, Integer.valueOf(48));
		OUTBOUND.put(PacketPlayOutRemoveEntityEffect.class, Integer.valueOf(49));
		OUTBOUND.put(ProtocolInjector.PacketPlayResourcePackSend.class, Integer.valueOf(50));
		OUTBOUND.put(PacketPlayOutRespawn.class, Integer.valueOf(51));
		OUTBOUND.put(PacketPlayOutEntityHeadRotation.class, Integer.valueOf(52));
		OUTBOUND.put(PacketPlayOutHeldItemSlot.class, Integer.valueOf(55));
		OUTBOUND.put(PacketPlayOutScoreboardDisplayObjective.class, Integer.valueOf(56));
		OUTBOUND.put(PacketPlayOutEntityMetadata.class, Integer.valueOf(57));
		OUTBOUND.put(PacketPlayOutAttachEntity.class, Integer.valueOf(58));
		OUTBOUND.put(PacketPlayOutEntityVelocity.class, Integer.valueOf(59));
		OUTBOUND.put(PacketPlayOutEntityEquipment.class, Integer.valueOf(60));
		OUTBOUND.put(PacketPlayOutExperience.class, Integer.valueOf(61));
		OUTBOUND.put(PacketPlayOutUpdateHealth.class, Integer.valueOf(62));
		OUTBOUND.put(PacketPlayOutScoreboardObjective.class, Integer.valueOf(63));
		OUTBOUND.put(PacketPlayOutMount.class, Integer.valueOf(64));
		OUTBOUND.put(PacketPlayOutScoreboardTeam.class, Integer.valueOf(65));
		OUTBOUND.put(PacketPlayOutScoreboardScore.class, Integer.valueOf(66));
		OUTBOUND.put(PacketPlayOutSpawnPosition.class, Integer.valueOf(67));
		OUTBOUND.put(PacketPlayOutUpdateTime.class, Integer.valueOf(68));
		OUTBOUND.put(ProtocolInjector.PacketTitle.class, Integer.valueOf(69));
		OUTBOUND.put(PacketPlayOutUpdateSign.class, Integer.valueOf(70));
		OUTBOUND.put(ProtocolInjector.PacketTabHeaderFooter.class, Integer.valueOf(72));
		OUTBOUND.put(PacketPlayOutCollect.class, Integer.valueOf(73));
		OUTBOUND.put(PacketPlayOutEntityTeleport.class, Integer.valueOf(74));
		OUTBOUND.put(PacketPlayOutUpdateAttributes.class, Integer.valueOf(75));
		OUTBOUND.put(PacketPlayOutEntityEffect.class, Integer.valueOf(76));
	}
}